name: "release-dev"

on:
  push:
    branches:
      - master

jobs:
  build-push-container:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build/Push container
        run: |
          export VERSION=$(grep 'version = "' math_api/pyproject.toml | head -1 | awk -F'"' '{print $2}')
          export CONTAINER_NAME=ghcr.io/nicogelders/cm-training:$VERSION-dev
          docker build . --tag $CONTAINER_NAME
          docker push $CONTAINER_NAME
